config/routes.rb
Cashflow2::Application.routes.draw do
  get "users/index"
  
  resources :users

  devise_for :users, :path => 'auth'

  get "dashboard/index"

  resources :transaction_types

  resources :transactions
  
  
  
  

  root :to => "dashboard#index"

end

app/models/expense.rb
class Expense < Transaction
  def amount
    -super
  end
end

app/models/income.rb
class Income < Transaction
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :user
  
  validates_presence_of :amount, :name, :frequency, :start_date
  
  def display_frequency
    case frequency
    when 'once_per_week' then 'Weekly'
    when 'once_per_day' then 'Daily'
    end
  end

  def to_hash
    money_stream = {}
    date = start_date
    begin
      money_stream[date] = amount
      date = case frequency
      when 'once_per_week' then date + 1.week
      when 'once_per_day' then date + 1.day
      end
    end while date <= 1.year.from_now.to_date
    money_stream
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :transactions
  

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :base_balance

  def balance_plan(base_balance, total_transfers = {})
    day_before_balance = base_balance
    years_balances = {}
    today = Date.today
    0.upto(364) do |u|
      date = today + u.days
      years_balances[date] = day_before_balance + (total_transfers[date] || 0)
      day_before_balance = years_balances[date]
    end
    
    years_balances
  end

  def total_transfers
    total_cash_stream = {}
    @user_transactions = transactions.find(:all)
    @user_transactions.each do |transaction|
      transaction.to_hash.each_pair do |k,v|
        total_cash_stream[k] ||= 0
        total_cash_stream[k] += v
      end
    end
    total_cash_stream
  end

  def to_s
    email
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def admin_logged_in
    redirect_to dashboard_index_path unless current_user.admin?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController  
  
  def index
    if user_signed_in?
      # @transactions = current_user.transactions.all
      @base_balance = current_user.base_balance
      @total_transfers = current_user.total_transfers
      @balance_plan = current_user.balance_plan(@base_balance || 0, @total_transfers || 0)
    else
      @transactions = Transactions.all
    end
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  
  # GET /transactions
  def index
    @transactions = current_user.transactions.all
  end

  # GET /transactions/1
  def show
    @transaction = Transaction.find(params[:id])
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  def create
    klass = params[:transaction].delete(:type).constantize
    @transaction = klass.new(params[:transaction])
    @transaction.user = current_user
    
    if @transaction.save
      flash[:notice] = "You have created a new Transaction"
      redirect_to transactions_path
    else
      render :new
    end
  end

  # PUT /transactions/1
  def update
    @transaction = Transaction.find(params[:id])
    
    if @transaction.update_attributes params[:transaction]
      redirect_to transaction_path(@transaction)
    else
      render :edit
    end 
  end

  # DELETE /transactions/1
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.find(:all)
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    current_user
  end

  # PUT /users/1
  def update
    if current_user.update_attributes params[:user]
      redirect_to dashboard_index_path
    else
      render :edit
    end 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<div>
	<h4>Base Balance</h4>
	<ul><%= number_to_currency(@base_balance) %></ul>
	<ul><%= render "users/balance" %></ul><br />
</div>

<div>
	<h4>Transactions</h4>
	<ul><%= @total_transfers %></ul>
</div>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cashflow2</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id="main">
		<header>
			<div id="toolbar">
			<% if user_signed_in? %>
				Signed in as <%= link_to current_user, edit_user_registration_path %>
				<%= link_to "Sign Out", destroy_user_session_path %>
				<%= link_to "Dashboard", dashboard_index_path %>
			<% else %>
				<%= link_to "Sign In", new_user_session_path %>
				<%= link_to "Register", new_user_registration_path %>
			<% end %>
			</div>
		</header>
		
		<h4>Session</h4>	<%= debug(session) %>
		<h4>Params</h4>	<%= debug(params) %>
		<h4>Response</h4>	<%= debug(response) %>
				
<div id="container">
	
<%= yield %>

</div>

</body>
</html>

app/views/transactions/_form.html.erb
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br />
    <%= form.text_field :name %><br />

    <%= form.label :amount %><br />
    <%= form.text_field :amount %><br />
	
	  <%= form.label :start_date %><br />
    <%= form.text_field :start_date %><br />

	  <%= form.label :type, "Transaction Type" %><br />
    <%= form.select(:type, ['Expense', 'Income']) %><br />

		<%= form.label :frequency %><br />		
	 	<%= form.select(:frequency, [['Weekly', 'once_per_week'], ['Daily', 'once_per_day']]) %>
  </div>

  <div class="actions">
    <%= form.submit "Create New Transaction" %>
  </div>
<%# end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= form_for(@transaction, :url => transaction_path(@transaction), :as => :transaction) do |form| %>
	<%= render form %>
<% end %>

<%= link_to 'Show', transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.name %></td>
		<td><%= transaction.amount %></td>
		<td><%= transaction.display_frequency %></td>
		<td><%= transaction.class.name %></td>
    <td><%= link_to 'Show', transaction_path(transaction) %></td>
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction_path(transaction), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= form_for(@transaction, :url => transactions_path, :as => :transaction) do |form| %>
	<%= render form %>
<% end %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @transaction.name %><br />
	<b>Type:</b>
	<%= @transaction.class.name %><br />
	<b>Amount: $</b>
	<%= @transaction.amount%><br />
	<b>Frequency:</b>
	<%= @transaction.display_frequency %>
</p>


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/users/_balance.html.erb
<%= form_for(current_user) do |f| %>

  <div class="field">
    <%= f.label :base_balance %><br />
    <%= f.text_field :base_balance %>
  </div>
  <div class="actions">
    <%= f.submit "Update Base Balance"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User Status</h1>

<%= render 'balance' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_index_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
		<td><%= user.base_balance %>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
  </tr>
<% end %>
</table>

<p>Find me in app/views/user/index.html.erb</p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Balance:</b>
  <%= current_user.base_balance %><br />
	<%= current_user.balance_plan %><br />
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_index_path %>